speed_limiter:
    ros__parameters:
        stop_boundary: 400.0
        slow_boundary: 800.0
        hysteresis: 50.0

estop_monitor:
    ros__parameters:
        trigger_time_ms: 12000

proximity_sensor:
    ros__parameters:
        sample_time_ms: 500
        distance_series: [
            850.0,
            840.0,
            830.0,
            820.0,
            810.0,
            800.0,
            810.0,
            820.0,
            810.0,
            800.0,
            810.0,
            800.0,
            790.0,
            780.0,
            470.0,
            460.0,
            450.0,
            440.0,
            430.0,
            420.0,
            410.0,
            400.0,
            410.0,
            420.0,
            400.0,
            390.0,
            380.0,
            200.0,
            800.0,
            870.0,
            900.0,
            1000.0,
        ]
